services:
    blast_profiler.profiler.collector:
        class: Blast\Bundle\ProfilerBundle\Collector\Collector

    blast_profiler.profiler.abstract_collector:
        abstract: true
        public: false
        calls:
            - [setCollector, ['@blast_profiler.profiler.collector']]

    blast_profiler.profiler.base_collector:
        parent: blast_profiler.profiler.abstract_collector
        class: Blast\Bundle\ProfilerBundle\Collector\BaseCollector
        public: false
        tags:
             -
                name:     data_collector
                template: BlastProfilerBundle:Collector:toolbar.html.twig
                id:       blast.base_collector
